/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.crud;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.HashMap;
import java.util.Map;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Luis Antonio
 */
public class FrmProductos extends javax.swing.JFrame  {
    // extends javax.swing.JInternalFrame
    //  extends javax.swing.JFrame 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmProductos.class.getName());

    /**
     * Creates new form FrmProductos
     */
    public FrmProductos() {
        initComponents();
        
        //setLocationRelativeTo(null);

        txtId.setEnabled(false);

        cargarCategorias();

        listarProductos();
        
        estadoInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cboCategoria = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        lblIdProducto = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(560, 420));

        txtId.setEnabled(false);
        txtId.addActionListener(this::txtIdActionPerformed);

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Gestión de Productos");

        lblIdProducto.setText("Id:");

        lblProducto.setText("Producto:");

        lblCategoria.setText("Categoría:");

        lblPrecio.setText("Precio:");

        lblStock.setText("Stock:");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdProducto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCategoria, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProducto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(cboCategoria, 0, 272, Short.MAX_VALUE)
                            .addComponent(lblTitulo)
                            .addComponent(txtId)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio)
                    .addComponent(lblStock)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Map<String, Integer> categorias = new HashMap<>();
    
    private void cargarCategorias() {

        cboCategoria.removeAllItems();
        categorias.clear();

        String sql =
            "SELECT id_categoria, nombre " +
            "FROM categoria " +
            "ORDER BY nombre";

        try (
            Connection cn = Conexion.conectar();
            PreparedStatement ps = cn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery()
        ) {

            while (rs.next()) {

                int id = rs.getInt("id_categoria");

                String nombre = rs.getString("nombre");

                cboCategoria.addItem(nombre);

                categorias.put(nombre, id);
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,"Error al cargar categorías: "+ e.getMessage());
        }
    }
    
    private void habilitarCampos(boolean estado) {

        txtNombre.setEnabled(estado);
        cboCategoria.setEnabled(estado);
        txtPrecio.setEnabled(estado);
        txtStock.setEnabled(estado);
    }
    
    private void estadoInicial() {

        habilitarCampos(false);

        btnNuevo.setEnabled(true);

        btnGuardar.setEnabled(false);
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnCancelar.setEnabled(false);
    }
  
    private void estadoNuevo() {

        habilitarCampos(true);

        btnNuevo.setEnabled(false);

        btnGuardar.setEnabled(true);
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);

        btnCancelar.setEnabled(true);
    }

    private void listarProductos() {

//        DefaultTableModel modelo =new DefaultTableModel();
//
//        modelo.addColumn("ID");
//        modelo.addColumn("Producto");
//        modelo.addColumn("Categoría");
//        modelo.addColumn("Precio");
//        modelo.addColumn("Stock");

    DefaultTableModel modelo = new DefaultTableModel( new Object[]{ "ID", "Producto", "Categoría", "Precio", "Stock"}, 0 ) { @Override public boolean isCellEditable(int row, int column) { return false; } };

        String sql =
            "SELECT p.id_producto, " +
            "       p.nombre, " +
            "       c.nombre AS categoria, " +
            "       p.precio, " +
            "       p.stock " +
            "FROM producto p " +
            "INNER JOIN categoria c " +
            "ON p.id_categoria = c.id_categoria " +
            "ORDER BY p.id_producto";

        try (
            Connection cn = Conexion.conectar();
            PreparedStatement ps = cn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery()
        ) {

            while (rs.next()) {

                Object[] fila = {
                    rs.getInt("id_producto"),
                    rs.getString("nombre"),
                    rs.getString("categoria"),
                    rs.getDouble("precio"),
                    rs.getInt("stock")
                };

                modelo.addRow(fila);
            }

            tblProductos.setModel(modelo);

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,"Error al listar productos: "+ e.getMessage());
        }
    }
    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void guardarProducto() {

        if (!validarCampos()) {
            return;
        }

        Double precio = obtenerPrecioValido();

        if (precio == null) {
            return;
        }

        Integer stock = obtenerStockValido();

        if (stock == null) {
            return;
        }

        String nombre = txtNombre.getText().trim();

        String categoria = cboCategoria.getSelectedItem().toString();

        int idCategoria = categorias.get(categoria);

        String sql =
            "INSERT INTO producto " +
            "(nombre, id_categoria, precio, stock) " +
            "VALUES (?, ?, ?, ?)";

        try (
            Connection cn = Conexion.conectar();
            PreparedStatement ps = cn.prepareStatement(sql)
        ) {

            ps.setString(1, nombre);
            ps.setInt(2, idCategoria);
            ps.setDouble(3, precio);
            ps.setInt(4, stock);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,"Producto registrado correctamente");

            listarProductos();
            limpiar();
            estadoInicial();

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,"Error al registrar: "+ e.getMessage());
        }
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarProducto();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        int fila = tblProductos.getSelectedRow();

        if (fila >= 0) {

            txtId.setText(tblProductos.getValueAt(fila, 0).toString());

            txtNombre.setText(tblProductos.getValueAt(fila, 1).toString());

            cboCategoria.setSelectedItem(tblProductos.getValueAt(fila, 2).toString());

            txtPrecio.setText(tblProductos.getValueAt(fila, 3).toString());

            txtStock.setText(tblProductos.getValueAt(fila, 4).toString());
            
            estadoEdicion();
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizarProducto();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarProducto();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
        estadoNuevo();
        txtNombre.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();

        tblProductos.clearSelection();

        estadoInicial();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void estadoEdicion() {

        habilitarCampos(true);

        btnNuevo.setEnabled(false);
        btnGuardar.setEnabled(false);

        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);

        btnCancelar.setEnabled(true);
    }
    
    private void limpiar() {

        txtId.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtStock.setText("");

        if (cboCategoria.getItemCount() > 0) {
            cboCategoria.setSelectedIndex(0);
        }
        
        tblProductos.clearSelection();
    }
    private void actualizarProducto() {

        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,"Seleccione un producto");
            return;
        }

        Double precio = obtenerPrecioValido();

        if (precio == null) {
            return;
        }

        Integer stock = obtenerStockValido();

        if (stock == null) {
            return;
        }
        
        try {

            int idProducto = Integer.parseInt(txtId.getText());

            String nombre = txtNombre.getText().trim();

            //double precio = Double.parseDouble(txtPrecio.getText());

            //int stock = Integer.parseInt( txtStock.getText());

            String categoria = cboCategoria.getSelectedItem().toString();

            int idCategoria = categorias.get(categoria);

            String sql =
                "UPDATE producto " +
                "SET nombre = ?, " +
                "id_categoria = ?, " +
                "precio = ?, " +
                "stock = ? " +
                "WHERE id_producto = ?";

            try (
                Connection cn = Conexion.conectar();

                PreparedStatement ps = cn.prepareStatement(sql)
            ) {

                ps.setString(1, nombre);
                ps.setInt(2, idCategoria);
                ps.setDouble(3, precio);
                ps.setInt(4, stock);
                ps.setInt(5, idProducto);

                ps.executeUpdate();

                JOptionPane.showMessageDialog( this, "Producto actualizado");

                limpiar();

                listarProductos();
                
                estadoInicial();
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,"Error: " + e.getMessage());
        }
    }
    
    private void eliminarProducto() {

        if (txtId.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this,"Seleccione un producto");

            return;
        }

        int respuesta =
            JOptionPane.showConfirmDialog(this,"¿Desea eliminar el producto?", "Confirmar",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);

        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }

        String sql =
            "DELETE FROM producto " +
            "WHERE id_producto = ?";

        try (
            Connection cn = Conexion.conectar();

            PreparedStatement ps = cn.prepareStatement(sql)
        ) {

            int id = Integer.parseInt( txtId.getText());

            ps.setInt(1, id);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,"Producto eliminado");

            limpiar();

            listarProductos();
            
            estadoInicial();

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,"Error al eliminar: "+ e.getMessage());
        }
    }
    
    private boolean validarCampos() {

        if (txtNombre.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this,"Ingrese el nombre del producto");

            txtNombre.requestFocus();

            return false;
        }

        if (cboCategoria.getSelectedItem() == null) {

            JOptionPane.showMessageDialog(this,"Seleccione una categoría");

            return false;
        }

        if (txtPrecio.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this,"Ingrese el precio");

            txtPrecio.requestFocus();

            return false;
        }

        if (txtStock.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Ingrese el stock");

            txtStock.requestFocus();

            return false;
        }

        return true;
    }
    
    private Double obtenerPrecioValido() {

        try {

            double precio =
                Double.parseDouble(
                    txtPrecio.getText().trim()
                );

            if (precio <= 0) {

                JOptionPane.showMessageDialog(
                    this,
                    "El precio debe ser mayor que cero"
                );

                txtPrecio.requestFocus();
                return null;
            }

            return precio;

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                this,
                "Ingrese un precio válido"
            );

            txtPrecio.requestFocus();
            return null;
        }
    }
    
    private Integer obtenerStockValido() {

        try {

            int stock =
                Integer.parseInt(
                    txtStock.getText().trim()
                );

            if (stock < 0) {

                JOptionPane.showMessageDialog(
                    this,
                    "El stock no puede ser negativo"
                );

                txtStock.requestFocus();
                return null;
            }

            return stock;

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                this,
                "Ingrese un stock válido"
            );

            txtStock.requestFocus();
            return null;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmProductos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblIdProducto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
